### ISSUE TITLE
[BA] provide project documentation

### ISSUE THREAD

**Issue by Swop4a** [Swop4a/dev-logger#18]
Provide project documentation for more details description of tasks

**Comment by Swop4a** [comment]
@pyxarez 

* http://localhost:8085/posts/?tab=1&smart=false (GET)
* http://localhost:8085/posts/{postId} (GET)
* http://localhost:8085/posts (POST) - save
* http://localhost:8085/posts (PUT) - update
* http://localhost:8085/posts/{postId} (DELETE)

**Comment by pyxarez** [comment]
pezdato!
